# fly.toml app configuration file generated for fleaclock on 2024-01-20T17:55:50+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "larasvelte"
primary_region = "nrt"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.3"

[env]
  APP_ENV = "production"
  BROADCAST_DRIVER = "log"
  CACHE_DRIVER = "file"
  DB_CONNECTION = "pgsql"
  DB_DATABASE = "postgres"
  DB_HOST = "db.gmeqvdtoqxiuhccadhfk.supabase.co"
  DB_PORT = "5432"
  DB_USERNAME = "postgres"
  FILESYSTEM_DISK = "local"
  LOG_CHANNEL = "stderr"
  LOG_DEPRECATIONS_CHANNEL = "null"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  QUEUE_CONNECTION = "sync"
  SESSION_DRIVER = "cookie"
  SESSION_LIFETIME = "120"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
